# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe Api::V1::ContractsController, type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Contract. As you add validations to Contract, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {{
    name: "CompanyTCH",
    week_start_time: 19,
    week_end_time: 24,
    weekend_start_time: 10,
    weekend_end_time: 24 }
    #skip('Add a hash of attributes valid for your model')
  }

  let(:invalid_attributes) {{
    name: "",
    week_start_time: NULL,
    week_end_time:NULL ,
    weekend_start_time: NULL ,
    weekend_end_time:NULL  }
    skip('Add a hash of attributes invalid for your model')
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ContractsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe 'GET api/v1/index' do
    let(:contract) { Contract.create(name: 'CompanyTCH', week_start_time: 19, week_end_time: 24, weekend_start_time: 10, weekend_end_time: 24) }
    it 'renders a successful response' do
      #Contract.create! valid_attributes
      get api_v1_contracts_path, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET api/v1/show' do
    contract =  let(:contract) { Contract.create(name: 'CompanyTCH', week_start_time: 19, week_end_time: 24, weekend_start_time: 10, weekend_end_time: 24) }
    it 'renders a successful response' do
      #contract = Contract.create! valid_attributes
      get api_v1_contract_path(contract), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST api/v1/create' do
   # let(:contract) { Contract.create(name: 'CompanyTCH', week_start_time: 19, week_end_time: 24, weekend_start_time: 10, weekend_end_time: 24) }

    context 'with valid parameters' do
      it 'creates a new Contract' do
        expect {
          post '/api/v1/contracts',
               params: { contract: valid_attributes },
               headers: valid_headers, as: :json
        }.to change(Contract, :count).by(1)
      end

      it 'renders a JSON response with the new contract' do
        post '/api/v1/contracts',
             params: { name: 'CompanyTCH', week_start_time: 19, week_end_time: 24, weekend_start_time: 10, weekend_end_time: 24  }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Contract' do
        expect {
          post '/api/v1/contracts',
               params: { contract: invalid_attributes }, as: :json
        }.to change(Contract, :count).by(0)
      end

      it 'renders a JSON response with errors for the new contract' do
        post '/api/v1/contracts',
             params: { contract: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe 'PATCH api/v1/update' do
    context 'with valid parameters' do
      let(:new_attributes) {
        skip('Add a hash of attributes valid for your model')
      }

      it 'updates the requested contract' do
        contract = Contract.create! valid_attributes
        patch contract_url(contract),
              params: { contract: new_attributes }, headers: valid_headers, as: :json
        contract.reload
        skip('Add assertions for updated state')
      end

      it 'renders a JSON response with the contract' do
        contract = Contract.create! valid_attributes
        patch contract_url(contract),
              params: { contract: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the contract' do
        contract = Contract.create! valid_attributes
        patch contract_url(contract),
              params: { contract: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe 'DELETE api/v1/destroy' do
    it 'destroys the requested contract' do
      contract = Contract.create! valid_attributes
      expect {
        delete contract_url(contract), headers: valid_headers, as: :json
      }.to change(Contract, :count).by(-1)
    end
  end
end
